# Generated by Django 5.0.14 on 2025-08-23 22:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id_departamento",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id_distrito",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MedioContacto",
            fields=[
                (
                    "id_medio_contacto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_medio", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedioPago",
            fields=[
                ("id_medio_pago", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_medio", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Modalidad",
            fields=[
                ("id_modalidad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_modalidad", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PermisoPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("leads", "Leads"),
                            ("crear_lead", "Crear Lead"),
                            ("matriculas", "Matrículas"),
                            ("malla_curricular", "Malla Curricular"),
                            ("asistencia_presencial", "Asistencia Presencial"),
                            ("empleados", "Empleados"),
                            ("nuevo_empleado", "Nuevo empleado"),
                            ("documentacion", "Documentación"),
                            ("consulta_sql", "Consulta SQL"),
                            ("tablas_bd", "Tablas BD"),
                            ("poblar_bd", "Poblar BD"),
                            ("finanzas", "Finanzas"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramaAcademico",
            fields=[
                ("id_programa", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_programa", models.CharField(max_length=255)),
                (
                    "tipo_programa",
                    models.CharField(
                        choices=[
                            ("Curso", "Curso"),
                            ("Especialización", "Especialización"),
                            ("Carrera Técnica", "Carrera Técnica"),
                        ],
                        default="Curso",
                        max_length=50,
                    ),
                ),
                (
                    "duracion_meses",
                    models.IntegerField(default=1, verbose_name="Duración en meses"),
                ),
                (
                    "numero_pensiones",
                    models.IntegerField(default=1, verbose_name="Número de pensiones"),
                ),
                (
                    "precio_matricula",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_pension_virtual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_pension_presencial",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_curso_unico",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id_lead", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_completo", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nivel_estudios",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("Otro", "Otro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado_lead",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Atendido", "Atendido"),
                            ("No Atendido", "No Atendido"),
                            ("Convertido", "Convertido"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones generales"
                    ),
                ),
                (
                    "id_distrito",
                    models.ForeignKey(
                        db_column="id_distrito",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.distrito",
                    ),
                ),
                (
                    "id_medio_contacto",
                    models.ForeignKey(
                        db_column="id_medio_contacto",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.mediocontacto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "archivo_dni",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_clientes/",
                        verbose_name="Archivo DNI (PDF o Imagen)",
                    ),
                ),
                (
                    "archivo_partida",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_clientes/",
                        verbose_name="Partida de Nacimiento (PDF o Imagen)",
                    ),
                ),
                (
                    "id_lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="gestion.lead"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                ("id_matricula", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Retirado", "Retirado"),
                            ("Egresado", "Egresado"),
                        ],
                        default="Activo",
                        max_length=20,
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        db_column="id_cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.cliente",
                    ),
                ),
                (
                    "id_modalidad",
                    models.ForeignKey(
                        db_column="id_modalidad",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.modalidad",
                    ),
                ),
                (
                    "id_programa",
                    models.ForeignKey(
                        db_column="id_programa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.programaacademico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_mes", models.IntegerField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="gestion.curso"
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="malla",
                        to="gestion.programaacademico",
                    ),
                ),
            ],
            options={
                "ordering": ["programa", "numero_mes"],
                "unique_together": {("programa", "numero_mes")},
            },
        ),
        migrations.CreateModel(
            name="LeadInteresPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_lead",
                    models.ForeignKey(
                        db_column="id_lead",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.lead",
                    ),
                ),
                (
                    "id_programa",
                    models.ForeignKey(
                        db_column="id_programa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.programaacademico",
                    ),
                ),
            ],
            options={
                "db_table": "gestion_lead_interes_programa",
                "unique_together": {("id_lead", "id_programa")},
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="intereses",
            field=models.ManyToManyField(
                through="gestion.LeadInteresPrograma", to="gestion.programaacademico"
            ),
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id_provincia",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "id_departamento",
                    models.ForeignKey(
                        db_column="id_departamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.departamento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distrito",
            name="id_provincia",
            field=models.ForeignKey(
                db_column="id_provincia",
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.provincia",
            ),
        ),
        migrations.CreateModel(
            name="RolEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "permisos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles_con_permiso",
                        to="gestion.permisopersonalizado",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="programaacademico",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programas",
                to="gestion.sede",
            ),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_pago", models.DateTimeField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "concepto",
                    models.CharField(
                        choices=[
                            ("Matrícula", "Matrícula"),
                            ("Pensión", "Pensión"),
                            ("Pago Único", "Pago Único"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numero_cuota", models.IntegerField(blank=True, null=True)),
                (
                    "descuento_aplicado",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "archivo_comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprobantes_pagos/",
                        verbose_name="Comprobante de pago (PDF o imagen)",
                    ),
                ),
                (
                    "id_matricula",
                    models.ForeignKey(
                        db_column="id_matricula",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.matricula",
                    ),
                ),
                (
                    "id_medio_pago",
                    models.ForeignKey(
                        db_column="id_medio_pago",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.mediopago",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.sede",
                        verbose_name="Sede del ingreso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="gestion.sede"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="gestion.sede"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                (
                    "permisos_personalizados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuarios_con_permiso",
                        to="gestion.permisopersonalizado",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="gestion.rolempleado",
                    ),
                ),
                (
                    "user_django",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfesorPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.programaacademico",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        limit_choices_to={"rol__nombre": "Profesor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservacionMatricula",
            fields=[
                ("id_observacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_observacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de observación",
                    ),
                ),
                ("observacion", models.TextField(verbose_name="Observación")),
                (
                    "id_matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones_matricula",
                        to="gestion.matricula",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                        verbose_name="Usuario que registra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observación de Matrícula",
                "verbose_name_plural": "Observaciones de Matrículas",
                "ordering": ["-fecha_observacion"],
            },
        ),
        migrations.CreateModel(
            name="ObservacionLead",
            fields=[
                ("id_observacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_observacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de observación",
                    ),
                ),
                ("observacion", models.TextField(verbose_name="Observación")),
                (
                    "id_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones_lead",
                        to="gestion.lead",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                        verbose_name="Usuario que registra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observación de Lead",
                "verbose_name_plural": "Observaciones de Leads",
                "ordering": ["-fecha_observacion"],
            },
        ),
        migrations.AddField(
            model_name="matricula",
            name="id_usuario_inscripcion",
            field=models.ForeignKey(
                db_column="id_usuario_inscripcion",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas_realizadas",
                to="gestion.usuario",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="id_usuario_atencion",
            field=models.ForeignKey(
                db_column="id_usuario_atencion",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads_atendidos",
                to="gestion.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Interaccion",
            fields=[
                ("id_interaccion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha_interaccion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tipo_interaccion",
                    models.CharField(
                        choices=[
                            ("Llamada", "Llamada"),
                            ("Email", "Email"),
                            ("Reunión", "Reunión"),
                            ("WhatsApp", "WhatsApp"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resultado", models.TextField()),
                (
                    "id_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacciones",
                        to="gestion.lead",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_interaccion"],
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("dni", models.CharField(blank=True, max_length=8, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("banco", models.CharField(blank=True, max_length=100)),
                ("cuenta_bancaria", models.CharField(blank=True, max_length=30)),
                ("cci", models.CharField(blank=True, max_length=30)),
                ("cargo", models.CharField(max_length=100)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("tipo_contrato", models.CharField(blank=True, max_length=100)),
                (
                    "horas_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Horas según contrato",
                    ),
                ),
                (
                    "sueldo_basico",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tasa_afp",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.1,
                        max_digits=5,
                        verbose_name="Tasa AFP (ej: 0.125)",
                    ),
                ),
                (
                    "sueldo_por_hora",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "horas_extras",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "inasistencias",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "comisiones",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "bonos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "descuentos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "remuneracion_bruta",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "neto_mensual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "neto_quincenal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "aporte_empleador",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.sede",
                        verbose_name="Sede del empleado",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleado",
                        to="gestion.usuario",
                        verbose_name="Usuario del sistema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("archivo", models.FileField(upload_to="documentos_empleados/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("resena_admin", models.TextField(blank=True, null=True)),
                ("fecha_resena", models.DateTimeField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="gestion.empleado",
                    ),
                ),
                (
                    "usuario_admin_resena",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resenas_documentos",
                        to="gestion.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanillaEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField()),
                ("anio", models.IntegerField()),
                ("sueldo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "aportes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "descuentos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("neto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateField(default=django.utils.timezone.now)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planillas",
                        to="gestion.empleado",
                    ),
                ),
                (
                    "gasto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planilla_empleado",
                        to="gestion.gasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Planilla",
                "verbose_name_plural": "Pagos de Planilla",
                "unique_together": {("empleado", "mes", "anio")},
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("id_nota", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_nota",
                    models.CharField(
                        choices=[
                            ("Práctica", "Práctica"),
                            ("Teórica", "Teórica"),
                            ("Final", "Final"),
                            ("Recuperación", "Recuperación"),
                        ],
                        default="Final",
                        max_length=20,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Nota (0-20)"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "id_matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="gestion.matricula",
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "periodo_curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.periodocurso",
                        verbose_name="Curso/Mes",
                    ),
                ),
                (
                    "id_usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                        verbose_name="Usuario que registra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["-fecha_registro"],
                "unique_together": {("id_matricula", "periodo_curso", "tipo_nota")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                ("id_asistencia", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_clase", models.DateField(verbose_name="Fecha de Clase")),
                ("asistio", models.BooleanField(default=True, verbose_name="Asistió")),
                (
                    "justificacion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificación"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "id_matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="gestion.matricula",
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "periodo_curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.periodocurso",
                        verbose_name="Curso/Mes",
                    ),
                ),
                (
                    "id_usuario_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                        verbose_name="Usuario que registra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "ordering": ["-fecha_clase"],
                "unique_together": {("id_matricula", "periodo_curso", "fecha_clase")},
            },
        ),
    ]
