# Generated by Django 5.0.14 on 2025-06-22 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedioContacto',
            fields=[
                ('id_medio_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_medio_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id_modalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modalidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=255)),
                ('tipo_programa', models.CharField(choices=[('Carrera 3 años', 'Carrera 3 años'), ('Carrera 1 año', 'Carrera 1 año'), ('Curso 1 mes', 'Curso 1 mes')], max_length=50)),
                ('precio_matricula', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_pension_virtual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_pension_presencial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_curso_unico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_estudios', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_lead', models.CharField(choices=[('Atendido', 'Atendido'), ('No Atendido', 'No Atendido'), ('Pendiente', 'Pendiente'), ('Convertido', 'Convertido')], max_length=20)),
                ('id_distrito', models.ForeignKey(db_column='id_distrito', on_delete=django.db.models.deletion.PROTECT, to='gestion.distrito')),
                ('id_medio_contacto', models.ForeignKey(db_column='id_medio_contacto', on_delete=django.db.models.deletion.PROTECT, to='gestion.mediocontacto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('id_lead', models.OneToOneField(db_column='id_lead', on_delete=django.db.models.deletion.CASCADE, to='gestion.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Egresado', 'Egresado')], default='Activo', max_length=20)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.PROTECT, to='gestion.modalidad')),
                ('id_programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.PROTECT, to='gestion.programaacademico')),
                ('id_usuario_inscripcion', models.ForeignKey(db_column='id_usuario_inscripcion', on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_realizadas', to='gestion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(choices=[('Matrícula', 'Matrícula'), ('Pensión', 'Pensión'), ('Pago Único', 'Pago Único')], max_length=20)),
                ('numero_cuota', models.IntegerField(blank=True, null=True)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='gestion.matricula')),
                ('id_medio_pago', models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.PROTECT, to='gestion.mediopago')),
            ],
        ),
        migrations.CreateModel(
            name='LeadInteresPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.CASCADE, to='gestion.lead')),
                ('id_programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='gestion.programaacademico')),
            ],
            options={
                'db_table': 'gestion_lead_interes_programa',
                'unique_together': {('id_lead', 'id_programa')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='intereses',
            field=models.ManyToManyField(through='gestion.LeadInteresPrograma', to='gestion.programaacademico'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='gestion.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.CASCADE, to='gestion.provincia'),
        ),
        migrations.AddField(
            model_name='lead',
            name='id_usuario_atencion',
            field=models.ForeignKey(db_column='id_usuario_atencion', on_delete=django.db.models.deletion.PROTECT, related_name='leads_atendidos', to='gestion.usuario'),
        ),
    ]
