# Generated by Django 5.0.6 on 2024-06-23 04:47

from django.db import migrations

def poblar_datos(apps, schema_editor):
    # --- Asesores (Usuarios) ---
    # Usuario = apps.get_model('gestion', 'Usuario')
    # Usuario.objects.bulk_create([
    #     Usuario(nombre_usuario='Alesandra', rol='Asesor'),
    #     Usuario(nombre_usuario='Malu', rol='Asesor'),
    #     Usuario(nombre_usuario='Dayana', rol='Asesor'),
    # ])

    # --- Medios de Contacto ---
    MedioContacto = apps.get_model('gestion', 'MedioContacto')
    MedioContacto.objects.bulk_create([
        MedioContacto(nombre_medio='Instagram'),
        MedioContacto(nombre_medio='Facebook'),
        MedioContacto(nombre_medio='TikTok'),
        MedioContacto(nombre_medio='Contacto Directo'),
        MedioContacto(nombre_medio='Familiar'),
        MedioContacto(nombre_medio='Página Web'),
    ])

    # --- Programas Académicos ---
    ProgramaAcademico = apps.get_model('gestion', 'ProgramaAcademico')
    ProgramaAcademico.objects.bulk_create([
        ProgramaAcademico(nombre_programa='Enfermería', tipo_programa='Carrera 3 años', precio_matricula=200, precio_pension_presencial=450, precio_pension_virtual=350),
        ProgramaAcademico(nombre_programa='Agropecuaria', tipo_programa='Carrera 3 años', precio_matricula=200, precio_pension_presencial=420, precio_pension_virtual=320),
        ProgramaAcademico(nombre_programa='Administración de Empresas', tipo_programa='Carrera 3 años', precio_matricula=200, precio_pension_presencial=480, precio_pension_virtual=380),
    ])

    # --- Medios de Pago ---
    MedioPago = apps.get_model('gestion', 'MedioPago')
    MedioPago.objects.bulk_create([
        MedioPago(nombre_medio='Yape'),
        MedioPago(nombre_medio='Plin'),
        MedioPago(nombre_medio='Tarjeta de Crédito/Débito'),
        MedioPago(nombre_medio='Transferencia Bancaria'),
        MedioPago(nombre_medio='Efectivo'),
    ])

    # --- Modalidades ---
    Modalidad = apps.get_model('gestion', 'Modalidad')
    Modalidad.objects.bulk_create([
        Modalidad(nombre_modalidad='Presencial'),
        Modalidad(nombre_modalidad='Virtual'),
        Modalidad(nombre_modalidad='Semi-presencial'),
    ])

    # --- Ubigeo (Departamentos, Provincias, Distritos) ---
    Departamento = apps.get_model('gestion', 'Departamento')
    Provincia = apps.get_model('gestion', 'Provincia')
    Distrito = apps.get_model('gestion', 'Distrito')

    dep_arequipa = Departamento.objects.create(id_departamento='04', nombre='AREQUIPA')
    dep_lima = Departamento.objects.create(id_departamento='15', nombre='LIMA')

    prov_arequipa = Provincia.objects.create(id_provincia='0401', nombre='AREQUIPA', id_departamento=dep_arequipa)
    prov_lima = Provincia.objects.create(id_provincia='1501', nombre='LIMA', id_departamento=dep_lima)

    Distrito.objects.bulk_create([
        Distrito(id_distrito='040101', nombre='AREQUIPA', id_provincia=prov_arequipa),
        Distrito(id_distrito='040102', nombre='CAYMA', id_provincia=prov_arequipa),
        Distrito(id_distrito='040103', nombre='CERRO COLORADO', id_provincia=prov_arequipa),
        Distrito(id_distrito='040121', nombre='SOCABAYA', id_provincia=prov_arequipa),
        Distrito(id_distrito='150101', nombre='LIMA', id_provincia=prov_lima),
        Distrito(id_distrito='150117', nombre='MIRAFLORES', id_provincia=prov_lima),
        Distrito(id_distrito='150122', nombre='PUEBLO LIBRE', id_provincia=prov_lima),
        Distrito(id_distrito='150131', nombre='SAN ISIDRO', id_provincia=prov_lima),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_datos),
    ]
