# Generated by Django 5.0.14 on 2025-06-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_poblar_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='archivo_dni',
            field=models.FileField(blank=True, null=True, upload_to='documentos_clientes/', verbose_name='Archivo DNI (PDF o Imagen)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='archivo_partida',
            field=models.FileField(blank=True, null=True, upload_to='documentos_clientes/', verbose_name='Partida de Nacimiento (PDF o Imagen)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.lead'),
        ),
    ]
