# Generated by Django 5.0.14 on 2025-06-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_archivo_dni_cliente_archivo_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estado_lead',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido'), ('No Atendido', 'No Atendido'), ('Convertido', 'Convertido')], max_length=20),
        ),
    ]
