# Generated by Django 5.0.14 on 2025-06-23 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_usuario_user_django_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id_interaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_interaccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_interaccion', models.CharField(choices=[('Llamada', 'Llamada'), ('Email', 'Email'), ('Reunión', 'Reunión'), ('WhatsApp', 'WhatsApp'), ('Otro', 'Otro')], max_length=50)),
                ('resultado', models.TextField()),
                ('id_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='gestion.lead')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'ordering': ['-fecha_interaccion'],
            },
        ),
    ]
