# Generated by Django 5.0.14 on 2025-07-08 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_interaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones generales'),
        ),
        migrations.CreateModel(
            name='ObservacionLead',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_observacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de observación')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('id_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_lead', to='gestion.lead')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario', verbose_name='Usuario que registra')),
            ],
            options={
                'verbose_name': 'Observación de Lead',
                'verbose_name_plural': 'Observaciones de Leads',
                'ordering': ['-fecha_observacion'],
            },
        ),
    ]
