# Generated by Django 5.0.14 on 2025-07-08 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_lead_observaciones_observacionlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionMatricula',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_observacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de observación')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_matricula', to='gestion.matricula')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario', verbose_name='Usuario que registra')),
            ],
            options={
                'verbose_name': 'Observación de Matrícula',
                'verbose_name_plural': 'Observaciones de Matrículas',
                'ordering': ['-fecha_observacion'],
            },
        ),
    ]
