# Generated by Django 5.0.14 on 2025-07-08 00:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_observacionmatricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('tipo_periodo', models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral')], default='Mensual', max_length=20)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Período Activo')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.programaacademico', verbose_name='Programa Académico')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nota', models.CharField(choices=[('Práctica', 'Práctica'), ('Teórica', 'Teórica'), ('Final', 'Final'), ('Recuperación', 'Recuperación')], default='Final', max_length=20)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota (0-20)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.matricula', verbose_name='Matrícula')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario', verbose_name='Usuario que registra')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.periodoacademico', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_registro'],
                'unique_together': {('id_matricula', 'id_periodo', 'tipo_nota')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_clase', models.DateField(verbose_name='Fecha de Clase')),
                ('asistio', models.BooleanField(default=True, verbose_name='Asistió')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.matricula', verbose_name='Matrícula')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario', verbose_name='Usuario que registra')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.periodoacademico', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_clase'],
                'unique_together': {('id_matricula', 'id_periodo', 'fecha_clase')},
            },
        ),
    ]
