# Generated by Django 5.0.14 on 2025-07-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_periodoacademico_nota_asistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'ordering': ['numero_periodo'], 'verbose_name': 'Período Académico', 'verbose_name_plural': 'Períodos Académicos'},
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='id_programa',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='tipo_periodo',
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='numero_periodo',
            field=models.IntegerField(default=1, unique=True, verbose_name='Número de Período'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre_periodo',
            field=models.CharField(default='Período', max_length=100, verbose_name='Nombre del Período'),
        ),
    ]
