# Generated by Django 5.0.14 on 2025-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_periodoacademico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaacademico',
            name='duracion_meses',
            field=models.IntegerField(default=1, verbose_name='Duración en meses'),
        ),
        migrations.AddField(
            model_name='programaacademico',
            name='numero_pensiones',
            field=models.IntegerField(default=1, verbose_name='Número de pensiones'),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='tipo_programa',
            field=models.CharField(choices=[('Curso', 'Curso'), ('Especialización', 'Especialización'), ('Carrera Técnica', 'Carrera Técnica')], default='Curso', max_length=50),
        ),
    ]
