# Generated by Django 5.0.14 on 2025-07-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_programaacademico_duracion_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='archivo_comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/', verbose_name='Comprobante de pago (PDF o imagen)'),
        ),
    ]
