# Generated by Django 5.0.14 on 2025-07-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_pago_archivo_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=30)),
                ('cci', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100)),
                ('horas_contrato', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas según contrato')),
                ('sueldo_basico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sueldo_por_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inasistencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('comisiones', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remuneracion_bruta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('neto_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('neto_quincenal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aporte_empleador', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='gestion.usuario', verbose_name='Usuario del sistema')),
            ],
        ),
    ]
