# Generated by Django 5.0.14 on 2025-07-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
