# Generated by Django 5.0.14 on 2025-07-08 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_empleado_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='documentos_empleados/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('resena_admin', models.TextField(blank=True, null=True)),
                ('fecha_resena', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.empleado')),
                ('usuario_admin_resena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas_documentos', to='gestion.usuario')),
            ],
        ),
    ]
