# Generated by Django 5.0.14 on 2025-07-09 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remove_usuario_rol_nuevo_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mes', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.curso')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla', to='gestion.programaacademico')),
            ],
            options={
                'ordering': ['programa', 'numero_mes'],
                'unique_together': {('programa', 'numero_mes')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='periodo_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.periodocurso', verbose_name='Curso/Mes'),
        ),
        migrations.AddField(
            model_name='nota',
            name='periodo_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.periodocurso', verbose_name='Curso/Mes'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('id_matricula', 'periodo_curso', 'fecha_clase')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('id_matricula', 'periodo_curso', 'tipo_nota')},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='id_periodo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='id_periodo',
        ),
    ]
