# Generated by Django 5.0.14 on 2025-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_curso_periodocurso_alter_asistencia_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodoacademico',
            old_name='id_periodo',
            new_name='id',
        ),
    ]
