# Generated by Django 5.0.14 on 2025-07-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_rename_id_periodo_periodoacademico_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodoAcademico',
        ),
    ]
