# Generated by Django 5.0.14 on 2025-07-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_gasto_id_alter_ingreso_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.sede', verbose_name='Sede del ingreso'),
        ),
    ]
