# Generated by Django 5.0.14 on 2025-07-11 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_add_sede_to_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.sede', verbose_name='Sede del empleado'),
        ),
    ]
