# Generated by Django 5.0.14 on 2025-07-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_add_sede_to_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('crear_lead', 'Crear Lead'), ('matriculas', 'Matrículas'), ('malla_curricular', 'Malla Curricular'), ('asistencia_presencial', 'Asistencia Presencial'), ('empleados', 'Empleados'), ('nuevo_empleado', 'Nuevo empleado'), ('documentacion', 'Documentación'), ('consulta_sql', 'Consulta SQL'), ('tablas_bd', 'Tablas BD'), ('poblar_bd', 'Poblar BD'), ('finanzas', 'Finanzas')], max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos_personalizados',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_permiso', to='gestion.permisopersonalizado'),
        ),
    ]
