# Generated by Django 5.0.14 on 2025-07-17 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_permisopersonalizado_usuario_permisos_personalizados'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aportes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('neto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planillas', to='gestion.empleado')),
                ('gasto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planilla_empleado', to='gestion.gasto')),
            ],
            options={
                'verbose_name': 'Pago de Planilla',
                'verbose_name_plural': 'Pagos de Planilla',
                'unique_together': {('empleado', 'mes', 'anio')},
            },
        ),
    ]
