# Generated by Django 5.0.14 on 2025-08-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0028_planillaempleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="tasa_afp",
            field=models.DecimalField(
                decimal_places=4,
                default=0.1,
                max_digits=5,
                verbose_name="Tasa AFP (ej: 0.125)",
            ),
        ),
        migrations.AddField(
            model_name="rolempleado",
            name="permisos",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles_con_permiso",
                to="gestion.permisopersonalizado",
            ),
        ),
    ]
